//
//  repositories.swift
//  SupaGithubCoreKitTests
//
//  Created by Mohamed Ali on 20/06/2019.
//  Copyright © 2019 GeekDev. All rights reserved.
//

import Foundation

struct FakeData {}

extension FakeData {
    static var fakeRepositories = """
{
"total_count": 543238,
"incomplete_results": false,
"items": [
{
"id": 4311796,
"node_id": "MDEwOlJlcG9zaXRvcnk0MzExNzk2",
"name": "markdown-here",
"full_name": "adam-p/markdown-here",
"private": false,
"owner": {
"login": "adam-p",
"id": 425687,
"node_id": "MDQ6VXNlcjQyNTY4Nw==",
"avatar_url": "https://avatars0.githubusercontent.com/u/425687?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/adam-p",
"html_url": "https://github.com/adam-p",
"followers_url": "https://api.github.com/users/adam-p/followers",
"following_url": "https://api.github.com/users/adam-p/following{/other_user}",
"gists_url": "https://api.github.com/users/adam-p/gists{/gist_id}",
"starred_url": "https://api.github.com/users/adam-p/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/adam-p/subscriptions",
"organizations_url": "https://api.github.com/users/adam-p/orgs",
"repos_url": "https://api.github.com/users/adam-p/repos",
"events_url": "https://api.github.com/users/adam-p/events{/privacy}",
"received_events_url": "https://api.github.com/users/adam-p/received_events",
"type": "User",
"site_admin": false
},
"html_url": "https://github.com/adam-p/markdown-here",
"description": "Google Chrome, Firefox, and Thunderbird extension that lets you write email in Markdown and render it before sending.",
"fork": false,
"url": "https://api.github.com/repos/adam-p/markdown-here",
"forks_url": "https://api.github.com/repos/adam-p/markdown-here/forks",
"keys_url": "https://api.github.com/repos/adam-p/markdown-here/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/adam-p/markdown-here/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/adam-p/markdown-here/teams",
"hooks_url": "https://api.github.com/repos/adam-p/markdown-here/hooks",
"issue_events_url": "https://api.github.com/repos/adam-p/markdown-here/issues/events{/number}",
"events_url": "https://api.github.com/repos/adam-p/markdown-here/events",
"assignees_url": "https://api.github.com/repos/adam-p/markdown-here/assignees{/user}",
"branches_url": "https://api.github.com/repos/adam-p/markdown-here/branches{/branch}",
"tags_url": "https://api.github.com/repos/adam-p/markdown-here/tags",
"blobs_url": "https://api.github.com/repos/adam-p/markdown-here/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/adam-p/markdown-here/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/adam-p/markdown-here/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/adam-p/markdown-here/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/adam-p/markdown-here/statuses/{sha}",
"languages_url": "https://api.github.com/repos/adam-p/markdown-here/languages",
"stargazers_url": "https://api.github.com/repos/adam-p/markdown-here/stargazers",
"contributors_url": "https://api.github.com/repos/adam-p/markdown-here/contributors",
"subscribers_url": "https://api.github.com/repos/adam-p/markdown-here/subscribers",
"subscription_url": "https://api.github.com/repos/adam-p/markdown-here/subscription",
"commits_url": "https://api.github.com/repos/adam-p/markdown-here/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/adam-p/markdown-here/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/adam-p/markdown-here/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/adam-p/markdown-here/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/adam-p/markdown-here/contents/{+path}",
"compare_url": "https://api.github.com/repos/adam-p/markdown-here/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/adam-p/markdown-here/merges",
"archive_url": "https://api.github.com/repos/adam-p/markdown-here/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/adam-p/markdown-here/downloads",
"issues_url": "https://api.github.com/repos/adam-p/markdown-here/issues{/number}",
"pulls_url": "https://api.github.com/repos/adam-p/markdown-here/pulls{/number}",
"milestones_url": "https://api.github.com/repos/adam-p/markdown-here/milestones{/number}",
"notifications_url": "https://api.github.com/repos/adam-p/markdown-here/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/adam-p/markdown-here/labels{/name}",
"releases_url": "https://api.github.com/repos/adam-p/markdown-here/releases{/id}",
"deployments_url": "https://api.github.com/repos/adam-p/markdown-here/deployments",
"created_at": "2012-05-13T03:27:22Z",
"updated_at": "2019-06-19T20:23:39Z",
"pushed_at": "2019-05-11T14:08:34Z",
"git_url": "git://github.com/adam-p/markdown-here.git",
"ssh_url": "git@github.com:adam-p/markdown-here.git",
"clone_url": "https://github.com/adam-p/markdown-here.git",
"svn_url": "https://github.com/adam-p/markdown-here",
"homepage": "http://markdown-here.com",
"size": 16214,
"stargazers_count": 38701,
"watchers_count": 38701,
"language": "JavaScript",
"has_issues": true,
"has_projects": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": true,
"forks_count": 6629,
"mirror_url": null,
"archived": false,
"disabled": false,
"open_issues_count": 241,
"license": {
"key": "mit",
"name": "MIT License",
"spdx_id": "MIT",
"url": "https://api.github.com/licenses/mit",
"node_id": "MDc6TGljZW5zZTEz"
},
"topics": [],
"forks": 6629,
"open_issues": 241,
"watchers": 38701,
"default_branch": "master",
"score": 44.557266
},
{
"id": 24953448,
"node_id": "MDEwOlJlcG9zaXRvcnkyNDk1MzQ0OA==",
"name": "material-design-icons",
"full_name": "google/material-design-icons",
"private": false,
"owner": {
"login": "google",
"id": 1342004,
"node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
"avatar_url": "https://avatars1.githubusercontent.com/u/1342004?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/google",
"html_url": "https://github.com/google",
"followers_url": "https://api.github.com/users/google/followers",
"following_url": "https://api.github.com/users/google/following{/other_user}",
"gists_url": "https://api.github.com/users/google/gists{/gist_id}",
"starred_url": "https://api.github.com/users/google/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/google/subscriptions",
"organizations_url": "https://api.github.com/users/google/orgs",
"repos_url": "https://api.github.com/users/google/repos",
"events_url": "https://api.github.com/users/google/events{/privacy}",
"received_events_url": "https://api.github.com/users/google/received_events",
"type": "Organization",
"site_admin": false
},
"html_url": "https://github.com/google/material-design-icons",
"description": "Material Design icons by Google",
"fork": false,
"url": "https://api.github.com/repos/google/material-design-icons",
"forks_url": "https://api.github.com/repos/google/material-design-icons/forks",
"keys_url": "https://api.github.com/repos/google/material-design-icons/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/google/material-design-icons/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/google/material-design-icons/teams",
"hooks_url": "https://api.github.com/repos/google/material-design-icons/hooks",
"issue_events_url": "https://api.github.com/repos/google/material-design-icons/issues/events{/number}",
"events_url": "https://api.github.com/repos/google/material-design-icons/events",
"assignees_url": "https://api.github.com/repos/google/material-design-icons/assignees{/user}",
"branches_url": "https://api.github.com/repos/google/material-design-icons/branches{/branch}",
"tags_url": "https://api.github.com/repos/google/material-design-icons/tags",
"blobs_url": "https://api.github.com/repos/google/material-design-icons/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/google/material-design-icons/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/google/material-design-icons/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/google/material-design-icons/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/google/material-design-icons/statuses/{sha}",
"languages_url": "https://api.github.com/repos/google/material-design-icons/languages",
"stargazers_url": "https://api.github.com/repos/google/material-design-icons/stargazers",
"contributors_url": "https://api.github.com/repos/google/material-design-icons/contributors",
"subscribers_url": "https://api.github.com/repos/google/material-design-icons/subscribers",
"subscription_url": "https://api.github.com/repos/google/material-design-icons/subscription",
"commits_url": "https://api.github.com/repos/google/material-design-icons/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/google/material-design-icons/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/google/material-design-icons/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/google/material-design-icons/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/google/material-design-icons/contents/{+path}",
"compare_url": "https://api.github.com/repos/google/material-design-icons/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/google/material-design-icons/merges",
"archive_url": "https://api.github.com/repos/google/material-design-icons/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/google/material-design-icons/downloads",
"issues_url": "https://api.github.com/repos/google/material-design-icons/issues{/number}",
"pulls_url": "https://api.github.com/repos/google/material-design-icons/pulls{/number}",
"milestones_url": "https://api.github.com/repos/google/material-design-icons/milestones{/number}",
"notifications_url": "https://api.github.com/repos/google/material-design-icons/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/google/material-design-icons/labels{/name}",
"releases_url": "https://api.github.com/repos/google/material-design-icons/releases{/id}",
"deployments_url": "https://api.github.com/repos/google/material-design-icons/deployments",
"created_at": "2014-10-08T18:01:28Z",
"updated_at": "2019-06-19T20:57:16Z",
"pushed_at": "2019-04-12T18:02:27Z",
"git_url": "git://github.com/google/material-design-icons.git",
"ssh_url": "git@github.com:google/material-design-icons.git",
"clone_url": "https://github.com/google/material-design-icons.git",
"svn_url": "https://github.com/google/material-design-icons",
"homepage": "http://google.github.io/material-design-icons/",
"size": 47085,
"stargazers_count": 38193,
"watchers_count": 38193,
"language": "CSS",
"has_issues": true,
"has_projects": true,
"has_downloads": false,
"has_wiki": true,
"has_pages": true,
"forks_count": 7773,
"mirror_url": null,
"archived": false,
"disabled": false,
"open_issues_count": 550,
"license": {
"key": "apache-2.0",
"name": "Apache License 2.0",
"spdx_id": "Apache-2.0",
"url": "https://api.github.com/licenses/apache-2.0",
"node_id": "MDc6TGljZW5zZTI="
},
"topics": [
"android",
"icons",
"ios",
"material",
"material-design",
"sprites",
"web"
],
"forks": 7773,
"open_issues": 550,
"watchers": 38193,
"default_branch": "master",
"score": 78.98533
},
{
"id": 23357588,
"node_id": "MDEwOlJlcG9zaXRvcnkyMzM1NzU4OA==",
"name": "protobuf",
"full_name": "protocolbuffers/protobuf",
"private": false,
"owner": {
"login": "protocolbuffers",
"id": 26310541,
"node_id": "MDEyOk9yZ2FuaXphdGlvbjI2MzEwNTQx",
"avatar_url": "https://avatars1.githubusercontent.com/u/26310541?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/protocolbuffers",
"html_url": "https://github.com/protocolbuffers",
"followers_url": "https://api.github.com/users/protocolbuffers/followers",
"following_url": "https://api.github.com/users/protocolbuffers/following{/other_user}",
"gists_url": "https://api.github.com/users/protocolbuffers/gists{/gist_id}",
"starred_url": "https://api.github.com/users/protocolbuffers/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/protocolbuffers/subscriptions",
"organizations_url": "https://api.github.com/users/protocolbuffers/orgs",
"repos_url": "https://api.github.com/users/protocolbuffers/repos",
"events_url": "https://api.github.com/users/protocolbuffers/events{/privacy}",
"received_events_url": "https://api.github.com/users/protocolbuffers/received_events",
"type": "Organization",
"site_admin": false
},
"html_url": "https://github.com/protocolbuffers/protobuf",
"description": "Protocol Buffers - Google's data interchange format",
"fork": false,
"url": "https://api.github.com/repos/protocolbuffers/protobuf",
"forks_url": "https://api.github.com/repos/protocolbuffers/protobuf/forks",
"keys_url": "https://api.github.com/repos/protocolbuffers/protobuf/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/protocolbuffers/protobuf/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/protocolbuffers/protobuf/teams",
"hooks_url": "https://api.github.com/repos/protocolbuffers/protobuf/hooks",
"issue_events_url": "https://api.github.com/repos/protocolbuffers/protobuf/issues/events{/number}",
"events_url": "https://api.github.com/repos/protocolbuffers/protobuf/events",
"assignees_url": "https://api.github.com/repos/protocolbuffers/protobuf/assignees{/user}",
"branches_url": "https://api.github.com/repos/protocolbuffers/protobuf/branches{/branch}",
"tags_url": "https://api.github.com/repos/protocolbuffers/protobuf/tags",
"blobs_url": "https://api.github.com/repos/protocolbuffers/protobuf/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/protocolbuffers/protobuf/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/protocolbuffers/protobuf/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/protocolbuffers/protobuf/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/protocolbuffers/protobuf/statuses/{sha}",
"languages_url": "https://api.github.com/repos/protocolbuffers/protobuf/languages",
"stargazers_url": "https://api.github.com/repos/protocolbuffers/protobuf/stargazers",
"contributors_url": "https://api.github.com/repos/protocolbuffers/protobuf/contributors",
"subscribers_url": "https://api.github.com/repos/protocolbuffers/protobuf/subscribers",
"subscription_url": "https://api.github.com/repos/protocolbuffers/protobuf/subscription",
"commits_url": "https://api.github.com/repos/protocolbuffers/protobuf/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/protocolbuffers/protobuf/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/protocolbuffers/protobuf/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/protocolbuffers/protobuf/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/protocolbuffers/protobuf/contents/{+path}",
"compare_url": "https://api.github.com/repos/protocolbuffers/protobuf/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/protocolbuffers/protobuf/merges",
"archive_url": "https://api.github.com/repos/protocolbuffers/protobuf/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/protocolbuffers/protobuf/downloads",
"issues_url": "https://api.github.com/repos/protocolbuffers/protobuf/issues{/number}",
"pulls_url": "https://api.github.com/repos/protocolbuffers/protobuf/pulls{/number}",
"milestones_url": "https://api.github.com/repos/protocolbuffers/protobuf/milestones{/number}",
"notifications_url": "https://api.github.com/repos/protocolbuffers/protobuf/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/protocolbuffers/protobuf/labels{/name}",
"releases_url": "https://api.github.com/repos/protocolbuffers/protobuf/releases{/id}",
"deployments_url": "https://api.github.com/repos/protocolbuffers/protobuf/deployments",
"created_at": "2014-08-26T15:52:15Z",
"updated_at": "2019-06-19T19:45:16Z",
"pushed_at": "2019-06-19T16:38:40Z",
"git_url": "git://github.com/protocolbuffers/protobuf.git",
"ssh_url": "git@github.com:protocolbuffers/protobuf.git",
"clone_url": "https://github.com/protocolbuffers/protobuf.git",
"svn_url": "https://github.com/protocolbuffers/protobuf",
"homepage": "https://developers.google.com/protocol-buffers/",
"size": 56368,
"stargazers_count": 35119,
"watchers_count": 35119,
"language": "C++",
"has_issues": true,
"has_projects": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": true,
"forks_count": 9523,
"mirror_url": null,
"archived": false,
"disabled": false,
"open_issues_count": 623,
"license": {
"key": "other",
"name": "Other",
"spdx_id": "NOASSERTION",
"url": null,
"node_id": "MDc6TGljZW5zZTA="
},
"topics": [
"marshalling",
"protobuf",
"protobuf-runtime",
"protoc",
"protocol-buffers",
"protocol-compiler",
"rpc",
"serialization"
],
"forks": 9523,
"open_issues": 623,
"watchers": 35119,
"default_branch": "master",
"score": 73.54234
},
{
"id": 20300177,
"node_id": "MDEwOlJlcG9zaXRvcnkyMDMwMDE3Nw==",
"name": "guava",
"full_name": "google/guava",
"private": false,
"owner": {
"login": "google",
"id": 1342004,
"node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
"avatar_url": "https://avatars1.githubusercontent.com/u/1342004?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/google",
"html_url": "https://github.com/google",
"followers_url": "https://api.github.com/users/google/followers",
"following_url": "https://api.github.com/users/google/following{/other_user}",
"gists_url": "https://api.github.com/users/google/gists{/gist_id}",
"starred_url": "https://api.github.com/users/google/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/google/subscriptions",
"organizations_url": "https://api.github.com/users/google/orgs",
"repos_url": "https://api.github.com/users/google/repos",
"events_url": "https://api.github.com/users/google/events{/privacy}",
"received_events_url": "https://api.github.com/users/google/received_events",
"type": "Organization",
"site_admin": false
},
"html_url": "https://github.com/google/guava",
"description": "Google core libraries for Java",
"fork": false,
"url": "https://api.github.com/repos/google/guava",
"forks_url": "https://api.github.com/repos/google/guava/forks",
"keys_url": "https://api.github.com/repos/google/guava/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/google/guava/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/google/guava/teams",
"hooks_url": "https://api.github.com/repos/google/guava/hooks",
"issue_events_url": "https://api.github.com/repos/google/guava/issues/events{/number}",
"events_url": "https://api.github.com/repos/google/guava/events",
"assignees_url": "https://api.github.com/repos/google/guava/assignees{/user}",
"branches_url": "https://api.github.com/repos/google/guava/branches{/branch}",
"tags_url": "https://api.github.com/repos/google/guava/tags",
"blobs_url": "https://api.github.com/repos/google/guava/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/google/guava/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/google/guava/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/google/guava/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/google/guava/statuses/{sha}",
"languages_url": "https://api.github.com/repos/google/guava/languages",
"stargazers_url": "https://api.github.com/repos/google/guava/stargazers",
"contributors_url": "https://api.github.com/repos/google/guava/contributors",
"subscribers_url": "https://api.github.com/repos/google/guava/subscribers",
"subscription_url": "https://api.github.com/repos/google/guava/subscription",
"commits_url": "https://api.github.com/repos/google/guava/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/google/guava/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/google/guava/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/google/guava/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/google/guava/contents/{+path}",
"compare_url": "https://api.github.com/repos/google/guava/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/google/guava/merges",
"archive_url": "https://api.github.com/repos/google/guava/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/google/guava/downloads",
"issues_url": "https://api.github.com/repos/google/guava/issues{/number}",
"pulls_url": "https://api.github.com/repos/google/guava/pulls{/number}",
"milestones_url": "https://api.github.com/repos/google/guava/milestones{/number}",
"notifications_url": "https://api.github.com/repos/google/guava/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/google/guava/labels{/name}",
"releases_url": "https://api.github.com/repos/google/guava/releases{/id}",
"deployments_url": "https://api.github.com/repos/google/guava/deployments",
"created_at": "2014-05-29T16:23:17Z",
"updated_at": "2019-06-19T19:44:13Z",
"pushed_at": "2019-06-19T11:49:35Z",
"git_url": "git://github.com/google/guava.git",
"ssh_url": "git@github.com:google/guava.git",
"clone_url": "https://github.com/google/guava.git",
"svn_url": "https://github.com/google/guava",
"homepage": "",
"size": 251840,
"stargazers_count": 32246,
"watchers_count": 32246,
"language": "Java",
"has_issues": true,
"has_projects": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": true,
"forks_count": 7219,
"mirror_url": null,
"archived": false,
"disabled": false,
"open_issues_count": 821,
"license": {
"key": "apache-2.0",
"name": "Apache License 2.0",
"spdx_id": "Apache-2.0",
"url": "https://api.github.com/licenses/apache-2.0",
"node_id": "MDc6TGljZW5zZTI="
},
"topics": [
"guava",
"java"
],
"forks": 7219,
"open_issues": 821,
"watchers": 32246,
"default_branch": "master",
"score": 78.406784
},
{
"id": 34302698,
"node_id": "MDEwOlJlcG9zaXRvcnkzNDMwMjY5OA==",
"name": "serverless",
"full_name": "serverless/serverless",
"private": false,
"owner": {
"login": "serverless",
"id": 13742415,
"node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNzQyNDE1",
"avatar_url": "https://avatars0.githubusercontent.com/u/13742415?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/serverless",
"html_url": "https://github.com/serverless",
"followers_url": "https://api.github.com/users/serverless/followers",
"following_url": "https://api.github.com/users/serverless/following{/other_user}",
"gists_url": "https://api.github.com/users/serverless/gists{/gist_id}",
"starred_url": "https://api.github.com/users/serverless/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/serverless/subscriptions",
"organizations_url": "https://api.github.com/users/serverless/orgs",
"repos_url": "https://api.github.com/users/serverless/repos",
"events_url": "https://api.github.com/users/serverless/events{/privacy}",
"received_events_url": "https://api.github.com/users/serverless/received_events",
"type": "Organization",
"site_admin": false
},
"html_url": "https://github.com/serverless/serverless",
"description": "Serverless Framework – Build web, mobile and IoT applications with serverless architectures using AWS Lambda, Azure Functions, Google CloudFunctions & more! – ",
"fork": false,
"url": "https://api.github.com/repos/serverless/serverless",
"forks_url": "https://api.github.com/repos/serverless/serverless/forks",
"keys_url": "https://api.github.com/repos/serverless/serverless/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/serverless/serverless/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/serverless/serverless/teams",
"hooks_url": "https://api.github.com/repos/serverless/serverless/hooks",
"issue_events_url": "https://api.github.com/repos/serverless/serverless/issues/events{/number}",
"events_url": "https://api.github.com/repos/serverless/serverless/events",
"assignees_url": "https://api.github.com/repos/serverless/serverless/assignees{/user}",
"branches_url": "https://api.github.com/repos/serverless/serverless/branches{/branch}",
"tags_url": "https://api.github.com/repos/serverless/serverless/tags",
"blobs_url": "https://api.github.com/repos/serverless/serverless/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/serverless/serverless/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/serverless/serverless/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/serverless/serverless/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/serverless/serverless/statuses/{sha}",
"languages_url": "https://api.github.com/repos/serverless/serverless/languages",
"stargazers_url": "https://api.github.com/repos/serverless/serverless/stargazers",
"contributors_url": "https://api.github.com/repos/serverless/serverless/contributors",
"subscribers_url": "https://api.github.com/repos/serverless/serverless/subscribers",
"subscription_url": "https://api.github.com/repos/serverless/serverless/subscription",
"commits_url": "https://api.github.com/repos/serverless/serverless/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/serverless/serverless/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/serverless/serverless/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/serverless/serverless/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/serverless/serverless/contents/{+path}",
"compare_url": "https://api.github.com/repos/serverless/serverless/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/serverless/serverless/merges",
"archive_url": "https://api.github.com/repos/serverless/serverless/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/serverless/serverless/downloads",
"issues_url": "https://api.github.com/repos/serverless/serverless/issues{/number}",
"pulls_url": "https://api.github.com/repos/serverless/serverless/pulls{/number}",
"milestones_url": "https://api.github.com/repos/serverless/serverless/milestones{/number}",
"notifications_url": "https://api.github.com/repos/serverless/serverless/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/serverless/serverless/labels{/name}",
"releases_url": "https://api.github.com/repos/serverless/serverless/releases{/id}",
"deployments_url": "https://api.github.com/repos/serverless/serverless/deployments",
"created_at": "2015-04-21T03:48:40Z",
"updated_at": "2019-06-19T20:02:09Z",
"pushed_at": "2019-06-19T19:07:56Z",
"git_url": "git://github.com/serverless/serverless.git",
"ssh_url": "git@github.com:serverless/serverless.git",
"clone_url": "https://github.com/serverless/serverless.git",
"svn_url": "https://github.com/serverless/serverless",
"homepage": "https://serverless.com",
"size": 82407,
"stargazers_count": 30469,
"watchers_count": 30469,
"language": "JavaScript",
"has_issues": true,
"has_projects": true,
"has_downloads": true,
"has_wiki": false,
"has_pages": false,
"forks_count": 3373,
"mirror_url": null,
"archived": false,
"disabled": false,
"open_issues_count": 545,
"license": {
"key": "mit",
"name": "MIT License",
"spdx_id": "MIT",
"url": "https://api.github.com/licenses/mit",
"node_id": "MDc6TGljZW5zZTEz"
},
"topics": [
"aws",
"aws-lambda",
"azure-functions",
"google-cloud-functions",
"ibm-openwhisk",
"javascript",
"microservice",
"serverless",
"serverless-architectures",
"serverless-framework"
],
"forks": 3373,
"open_issues": 545,
"watchers": 30469,
"default_branch": "master",
"score": 42.224262
}
]
}
"""
    
}
