# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SupaGithub' do
  use_frameworks!
  pod 'Yalta'
  pod 'Kingfisher', '~> 5.0'
  pod 'PromiseKit', '~> 6.0'
  pod 'Moya', '~> 13.0'
  pod 'Reusable'
end

target 'SupaGithub_iOS' do
  use_frameworks!
  pod 'Yalta'
  pod 'PromiseKit', '~> 6.0'
  pod 'Reusable'
  pod 'Kingfisher', '~> 5.0'
end

target 'SupaGithubCoreKit' do
  use_frameworks!
  pod 'Moya', '~> 13.0'
  pod 'PromiseKit', '~> 6.0'
end

target 'SupaGithubCoreKitTests' do
  use_frameworks!
  pod 'PromiseKit', '~> 6.0'
end

target 'CoordinatorKit' do
  use_frameworks!
  pod 'Yalta'
end
